### ISSUE TITLE
Two HTML files present

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/warmup-exercise#22]
There are two HTML files, when only one is needed. Delete the one that is not necessary or is outdated.

<img width="719" alt="Screenshot 2024-04-25 at 5 34 51 PM" src="https://github.com/cse110-sp24-group10/warmup-exercise/assets/75578029/3271fa07-c6c9-4a94-aefc-c39ef7ff43cb">

**Comment by AntDaKnee** [comment]
Altair removed the file.
